// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dummy() {
  return window['go']['main']['App']['Dummy']();
}

export function FixPaths(arg1) {
  return window['go']['main']['App']['FixPaths'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function InitPaths(arg1) {
  return window['go']['main']['App']['InitPaths'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
