// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function Dummy():Promise<lib.Message>;

export function FixPaths(arg1:Array<string>):Promise<void>;

export function GetConfig():Promise<lib.AppConfig>;

export function InitPaths(arg1:Array<string>):Promise<void>;

export function SetConfig(arg1:lib.AppConfig):Promise<void>;
